version: 2

models:
  - name: dim_channels
    description: "Contains one row per Telegram channel."
    columns:
      - name: channel_name
        description: "The unique name of the Telegram channel"
        tests:
          - not_null
          - unique

  - name: fct_messages
    description: "Fact table with each Telegram message."
    columns:
      - name: telegram_message_id
        description: "Unique ID for each message."
        tests:
          - not_null
          - unique

      - name: view_count
        description: "Number of views for the message."
        tests:
          - not_null

  - name: dim_dates
    description: "Dimension table containing calendar dates for time-based analysis."
    columns:
      - name: date_id
        description: "Surrogate key for date (row number)"
        tests:
          - not_null
          - unique

      - name: date
        description: "Actual calendar date"
        tests:
          - not_null

      - name: year
        description: "Extracted year"
        tests:
          - not_null

      - name: month
        description: "Extracted month"
        tests:
          - not_null

      - name: day
        description: "Extracted day"
        tests:
          - not_null

      - name: weekday
        description: "Day of the week (e.g., Monday)"

      - name: year_month
        description: "Formatted year and month string"
